### ISSUE TITLE
Automatic Authorization

### ISSUE THREAD

**Issue by schancel** [JetBrains/teamcity-google-agent#8] opened 2017-12-01 02:44 UTC
It's not clear to me what needs to be done to ensure that the agent images that have been made will automatically authorize with the teamcity server.

Can you please either point me to the docs that detail what causes automatic authorization, or help me to update the documentation?

**Comment by dtretyakov** [comment] 2017-12-01 15:08
@schancel, this plugin should automatically authorize build agents. It matches them by name received from Google metadata service.

If agent connects to your teamcity server but appears in `Unauthorzed` tab, could you please take a look at the `teamcity-agent.log` which is available at the `Agent Logs` tab. Connected state on Agents -> Cloud page look like that:
![image](https://user-images.githubusercontent.com/1025927/33488526-39d9e2d4-d6b1-11e7-98ca-f4383771aed8.png)

If it does not connect to TeamCity server please connect via ssh/rdp to it and inspect `teamcity-agent.log` file in the file system.

Did you checked that agent was successfully connected to teamcity server and updated while [preparing](https://blog.jetbrains.com/teamcity/2017/06/run-teamcity-ci-builds-in-google-cloud/) this image?

Also you could share the [teamcity-agent.log](https://confluence.jetbrains.com/display/TCDL/Viewing+Build+Agent+Logs) and [teamcity-clouds.log](https://confluence.jetbrains.com/display/TCDL/TeamCity+Server+Logs) log files in [TeamCity tracker](https://youtrack.jetbrains.com/issues/TW) where supported private attachments.

**Comment by delaman** [comment] 2017-12-11 05:43
I am also having an issue with agents not automatically authorizing.  The image was made after the agent connected to the teamcity server.

I have attached the agents log file.  The file has been modified by me for security reasons.

[teamcity-agent.log](https://github.com/JetBrains/teamcity-google-agent/files/1546641/teamcity-agent.log)

**Comment by dtretyakov** [comment] 2017-12-11 10:12
@delaman, thanks for sharing the log, I found the cause:

```
[2017-12-11 05:16:24,930]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.afterAgentConfigurationLoaded for listener jetbrains.buildServer.clouds.google.GoogleMetadataReader$1: java.lang.UnsupportedClassVersionError: jetbrains/buildServer/clouds/google/GoogleAgentProperties : Unsupported major.minor version 52.0 
```

It'll update JVM compilation targets and let you know when the fix will be available.

**Comment by dtretyakov** [comment] 2017-12-11 14:43
@delaman, the problem with JVM 1.7 compatibility was fixed in [the latest snapshot build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityGoogleCloudAgent_Build&guest=1).

@schancel if you also running TeamCity build agent under JVM 1.7 please update this plugin too.

**Comment by dtretyakov** [comment] 2017-12-11 14:46
But anyway it's recommended to run TeamCity build agents under JVM 1.8. To specify desired JVM you could use [environment variables](https://confluence.jetbrains.com/display/TCDL/Setting+up+and+Running+Additional+Build+Agents#SettingupandRunningAdditionalBuildAgents-ConfiguringJava).

**Comment by delaman** [comment] 2017-12-11 16:19
@dtretyakov Thank you.   I updated to Java 1.8 and the issue was resolved.  Thanks.

**Closed** 2017-12-11 16:45 UTC
Labels: bug
